ciphertext3 = 'DOEESFDAWTSRJSXSHRZFHJGBIEAGIEOIGKWYANVWKVPHAAGYKNZLVVJBTUYPQROWRBREKSQUAMBUOYRELKSYENPZWPDHXOOFXRXOWACAISFGECNDOEHYFSZBZOKGIFLRHVIPPHBKVRWDPSGFQNDMDBJHBKPEAALLOAZHXDCBGEWXFBIMRHCVJTHXJVAWEAYRWSMJOACEESBXXIKVKVPHWMZYCRXQDYQMTYSNJDTTZNYKMGDXJOMKCJWTLGBFWIWZSFQDWWBYUYHMRBJOMHFBLOLWHBENOWGGENLGIGDAYJWPWNLWQHNIMASF';

keylen = 1;

counts = zeros(keylen,26);

for i = 1:size(ciphertext3,2)
   
    counts(1+mod(i-1,keylen), ciphertext3(i)-64) = counts(1+mod(i-1,keylen), ciphertext3(i)-64)+1;
    
end

for i = 1:keylen
   
   counts(i,:);
   [x y] = max(counts(i,:));
   char(y+64)%mod((y-6),26)+65)
    
end
    
